[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "rm-bdd"
version = "0.1.1a3"
description = "Binance Data Downloader"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "Your Name", email = "you@example.com" }
]
dependencies = [
    "aiohttp==3.13.3",
    "pyarrow==23.0.1",
    "pandas==3.0.1",
    "xmltodict==1.0.4",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["rm_bdd*"]

[tool.pytest.ini_options]
pythonpath = ["src"]
asyncio_mode = "auto"